### PR TITLE
[ROUTER] Change router access logging to JSON to be parsed by Logstash/Sumo

### PR DESCRIPTION
**Pull request by DanHoerst**

### CODE REVIEW

**Comment by DanHoerst** [comment]
@rfein-hearst this is pretty big for us with logstash. Does this mess up Sumo? Log messages end up looking like:

```
2016-06-17T02:25:06UTC deis-router[1]: { "@timestamp": "17/Jun/2016:02:25:06 +0000", 
"@fields": { "remote_addr": "10.12.12.248", "remote_user": "-", "bytes_sent": "441", 
"request_time": "0.007", "status": "405", "request": "HEAD /v1/nodes HTTP/1.1", 
"request_method": "HEAD", "upstream_addr": "10.12.15.228:33547", "upstream_response_time": "0.007", 
"http_host": "masterrecord.two-stage-us-east-1.hearstapps.net", "http_referer": "-", 
"http_user_agent": "python-requests/2.7.0 CPython/3.5.1 Linux/4.3.6-coreos" } }
```

**Comment by marksost** [comment]
LGTM go-wise

**Comment by rfein-hearst** [comment]
@miketheprogrammer any issues parsing this with Sumo?

**Comment by DanHoerst** [comment]
@miketheprogrammer @rfein-hearst Could I get an update on whether this would break Sumo this morning? Would like to get this in before launch to help us troubleshoot via Logstash.

**Comment by miketheprogrammer** [comment]
checking

**Comment by miketheprogrammer** [comment]
I dont think that deis core services go to the logspout, however i could be wrong. Regardless, anything that can be parsed with regex is fine.

**Pull request merged**
