### PR TITLE
Return 503 when failed health check 

### PR DESCRIPTION
**Pull request by aj-may**

### CODE REVIEW

**Comment by DanHoerst** [comment]
Scary!

**Review by terowz — APPROVED** [review]
LGTM

**Comment by terowz** [comment]
wow i like these...reviews

**Comment by terowz** [comment]
@DanHoerst @aj-may so now anything that should properly 404 will 503?

**Comment by marksost** [comment]
Tough call, could go either way here..

**Review by marksost — APPROVED** [review]

**Comment by lslaslo** [comment]
Madness

**Pull request merged**
